In [9]:
# 2장

In [10]:
"Hello, world! \t\t\n".strip()

'Hello, world!'

In [11]:
"Hello, world!".split()
# Hello,와 world! 사이에 공백이 2개 있다.

['Hello,', 'world!']

In [12]:
"Hello, world!".split(" ")
# Hello,와 world! 사이에 공백이 2개 있다.

['Hello,', 'world!']

In [13]:
"www.networksciencelab.com".split(".")

['www', 'networksciencelab', 'com']

In [14]:
", ".join(["alpha", "bravo", "charlie", "delta"])

'alpha, bravo, charlie, delta'

In [15]:
"-".join("1.617.305.1985".split("."))

'1-617-305-1985'

In [16]:
" ".join("This string\n\r has many\t\tspaces".split())

'This string has many spaces'

In [17]:
"www.networksciencelab.com".find(".com")

21

In [18]:
"www.networksciencelab.com".count(".")

2

In [19]:
# myList = list(set(myList))
# 위의 경우와 같이,
# 회원 명단을 조회하거나 중복 항목을 삭제하는 데 셋을 유용하게 사용할 수 있다.
# 중복된 아이템이 들어 있는 리스트를 셋으로 변환하면 중복된 아이템을 모두 삭제한다.

In [20]:
seq = ["alpha", "bravo", "charlie", "delta"]
dict(enumerate(seq))

{0: 'alpha', 1: 'bravo', 2: 'charlie', 3: 'delta'}

In [21]:
kseq = "abcd" # 문자열 또한, 순서열이다.
vseq = ["alpha", "bravo", "charlie", "delta"]
dict(zip(kseq, vseq))

{'a': 'alpha', 'b': 'bravo', 'c': 'charlie', 'd': 'delta'}

In [22]:
from collections import Counter
phrase = "a man a plan a canal panama"
cntr = Counter(phrase.split())
cntr.most_common()

[('a', 3), ('man', 1), ('plan', 1), ('canal', 1), ('panama', 1)]

In [23]:
cntrDict = dict(cntr.most_common())
cntrDict

{'a': 3, 'man': 1, 'plan': 1, 'canal': 1, 'panama': 1}

In [24]:
cntrDict['a']

3

In [25]:
import urllib.parse
URL = "http://networksciencelab.com/index.html;param?foo=bar#content"
urllib.parse.urlparse(URL)

ParseResult(scheme='http', netloc='networksciencelab.com', path='/index.html', params='param', query='foo=bar', fragment='content')

In [26]:
import re
re.split(r"\W", "Hello, world!")

['Hello', '', 'world', '']

In [27]:
# 인근에 위치한 비문자(non-letter)를 합친다.
re.split(r"\W+", "Hello, world!")

['Hello', 'world', '']

In [28]:
mo = re.match(r"\d+", "067 Starts with a number")
mo

<re.Match object; span=(0, 3), match='067'>

In [29]:
mo.end()

3

In [30]:
mo.start()

0

In [31]:
mo.group()

'067'

In [32]:
print(re.match(r"\d+", "Does not start with a number"))

None


In [33]:
re.search(r"[a-z]+", "0010010 Has at least one 010 letter 0010010", re.I)

<re.Match object; span=(8, 11), match='Has'>

In [34]:
# 대소문자를 구분하는 버전
re.search(r"[a-z]+", "0010010 Has at least one 010 letter 0010010")

<re.Match object; span=(9, 11), match='as'>

In [35]:
re.findall(r"[a-z]+", "0010010 Has at least one 010 letter 0010010", re.I)

['Has', 'at', 'least', 'one', 'letter']

In [36]:
re.sub(r"[a-z ]+", "[...]", "0010010 has at least one 010 letter 0010010")

'0010010[...]010[...]0010010'

In [37]:
import glob
glob.glob("*.txt")

[]

In [38]:
# 5장 : numpy 다루기

In [5]:
import numpy as np

In [6]:
numbers = np.array(range(1,11),copy=True)
numbers

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [7]:
ones = np.ones([2, 4], dtype=np.float64)
ones

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [8]:
zeros = np.zeros([2, 4], dtype=np.float64)
zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [9]:
empty = np.empty([2, 4], dtype=np.float64)
# 배열의 내용물이 항상 0인 것은 아니다.
empty

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [10]:
ones.shape
# 아직 변형되지 않았다면 원래 모양을 반환한다.

(2, 4)

In [11]:
numbers.ndim # len(numbers.shape)와 같다.

1

In [12]:
zeros.dtype

dtype('float64')

In [13]:
eye = np.eye(3, k=1)
eye

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [14]:
np_numbers = np.arange(2, 5, 0.25)
np_numbers

array([2.  , 2.25, 2.5 , 2.75, 3.  , 3.25, 3.5 , 3.75, 4.  , 4.25, 4.5 ,
       4.75])

In [15]:
np_inumbers = np_numbers.astype(np.int)
np_inumbers

array([2, 2, 2, 2, 3, 3, 3, 3, 4, 4, 4, 4])

In [52]:
sap = np.array(["MMM", "ABT", "ABBV", "ACN", "ACE", "ATVI", "ADBE", "ADT"])
sap

array(['MMM', 'ABT', 'ABBV', 'ACN', 'ACE', 'ATVI', 'ADBE', 'ADT'],
      dtype='<U4')

In [53]:
sap2d = sap.reshape(2, 4)
sap2d

array([['MMM', 'ABT', 'ABBV', 'ACN'],
       ['ACE', 'ATVI', 'ADBE', 'ADT']], dtype='<U4')

In [54]:
sap3d = sap.reshape(2, 2, 2)
sap3d

array([[['MMM', 'ABT'],
        ['ABBV', 'ACN']],

       [['ACE', 'ATVI'],
        ['ADBE', 'ADT']]], dtype='<U4')

In [55]:
sap2d.T #sas로 치면 transpose와 같이 전치가 된다.

array([['MMM', 'ACE'],
       ['ABT', 'ATVI'],
       ['ABBV', 'ADBE'],
       ['ACN', 'ADT']], dtype='<U4')

In [56]:
sap3d.swapaxes(1, 2)

array([[['MMM', 'ABBV'],
        ['ABT', 'ACN']],

       [['ACE', 'ADBE'],
        ['ATVI', 'ADT']]], dtype='<U4')

In [57]:
sap3d.transpose((0, 2, 1))

array([[['MMM', 'ABBV'],
        ['ABT', 'ACN']],

       [['ACE', 'ADBE'],
        ['ATVI', 'ADT']]], dtype='<U4')

In [58]:
dirty = np.array([9, 4, 1, -0.01, -0.02, -0.001])
whos_dirty = dirty < 0 # 불 배열을 불 인덱스로 사용한다.
whos_dirty

array([False, False, False,  True,  True,  True])

In [60]:
dirty[whos_dirty] = 0
# 모든 음수값을 0으로 바꾼다.
dirty

array([9., 4., 1., 0., 0., 0.])

In [61]:
linear = np.arange(-1, 1.1, 0.2)
(linear <= 0.5) & (linear >= -0.5)

array([False, False, False,  True,  True,  True,  True,  True, False,
       False, False])

In [62]:
sap[[1, 2, -1]]

array(['ABT', 'ABBV', 'ADT'], dtype='<U4')

In [63]:
sap2d[:, [1]]

array([['ABT'],
       ['ATVI']], dtype='<U4')

In [17]:
a = np.arange(4)

In [19]:
a

array([0, 1, 2, 3])

In [20]:
b = np.arange(1, 5)

In [21]:
b

array([1, 2, 3, 4])

In [22]:
a+b

array([1, 3, 5, 7])

In [65]:
a*5

array([ 0,  5, 10, 15])

In [66]:
noise = np.eye(4) + 0.01 * np.ones((4, ))
noise

array([[1.01, 0.01, 0.01, 0.01],
       [0.01, 1.01, 0.01, 0.01],
       [0.01, 0.01, 1.01, 0.01],
       [0.01, 0.01, 0.01, 1.01]])

In [67]:
noise = np.eye(4) + 0.01 * np.random.random([4, 4])
np.round(noise, 2)

array([[1.  , 0.  , 0.01, 0.  ],
       [0.  , 1.  , 0.  , 0.  ],
       [0.  , 0.  , 1.  , 0.01],
       [0.01, 0.  , 0.  , 1.  ]])

In [39]:
stocks = np.array([140.49, 0.97, 40.68, 41.53, 55.7, 57.21, 98.2, 99.19, 109.96, 111.47, 35.71, 36.27, 87.85, 89.11, 30.22, 30.91])
stocks

array([140.49,   0.97,  40.68,  41.53,  55.7 ,  57.21,  98.2 ,  99.19,
       109.96, 111.47,  35.71,  36.27,  87.85,  89.11,  30.22,  30.91])

In [41]:
stocks = stocks.reshape(8, 2).T
stocks

array([[140.49,  40.68,  55.7 ,  98.2 , 109.96,  35.71,  87.85,  30.22],
       [  0.97,  41.53,  57.21,  99.19, 111.47,  36.27,  89.11,  30.91]])

In [70]:
fall = np.greater(stocks[0], stocks[1])
fall

array([ True, False, False, False, False, False, False, False])

In [71]:
sap[fall]

array(['MMM'], dtype='<U4')

In [72]:
# 새 MMM 주식 가격이 결측치라고 가정해보자.
stocks[1, 0] = np.nan
np.isnan(stocks) # 결측치라면 True라고 나온다.

array([[False, False, False, False, False, False, False, False],
       [ True, False, False, False, False, False, False, False]])

In [73]:
stocks[np.isnan(stocks)] = 0
stocks

array([[140.49,  40.68,  55.7 ,  98.2 , 109.96,  35.71,  87.85,  30.22],
       [  0.  ,  41.53,  57.21,  99.19, 111.47,  36.27,  89.11,  30.91]])

In [74]:
changes = np.where(np.abs(stocks[1] - stocks[0]) > 1.00,
                   stocks[1] - stocks[0], 0)
changes

array([-140.49,    0.  ,    1.51,    0.  ,    1.51,    0.  ,    1.26,
          0.  ])

In [75]:
sap[np.nonzero(changes)]

array(['MMM', 'ABBV', 'ACE', 'ADBE'], dtype='<U4')

In [76]:
sap[np.abs(stocks[1] - stocks[0]) > 1.00]

array(['MMM', 'ABBV', 'ACE', 'ADBE'], dtype='<U4')

In [77]:
sap[         np.abs(stocks[0] - stocks[1])
   > np.mean(np.abs(stocks[0] - stocks[1]))]

array(['MMM'], dtype='<U4')

In [78]:
dna = "AGTCCGCGAATACAGGCTCGGT"
dna_as_array = np.array(list(dna))
dna_as_array

array(['A', 'G', 'T', 'C', 'C', 'G', 'C', 'G', 'A', 'A', 'T', 'A', 'C',
       'A', 'G', 'G', 'C', 'T', 'C', 'G', 'G', 'T'], dtype='<U1')

In [79]:
np.unique(dna_as_array)

array(['A', 'C', 'G', 'T'], dtype='<U1')

In [80]:
np.in1d(["MSFT", "MMM", "AAPL"], sap)

array([False,  True, False])

In [3]:
# 6장 : pandas 다루기

In [13]:
import pandas as pd
import numpy as np

In [14]:
# 마지막 값이 잘못되었다. 잠시 후에 이를 수정해보자.

In [15]:
inflation = pd.Series((2.2, 3.4, 2.8, 1.6, 2.3, 2.7, 3.4, 3.2, 2.8, 3.8, 
-0.4, 1.6, 3.2, 2.1, 1.5, 1.5))
inflation

0     2.2
1     3.4
2     2.8
3     1.6
4     2.3
5     2.7
6     3.4
7     3.2
8     2.8
9     3.8
10   -0.4
11    1.6
12    3.2
13    2.1
14    1.5
15    1.5
dtype: float64

In [16]:
len(inflation)

16

In [17]:
inflation.values

array([ 2.2,  3.4,  2.8,  1.6,  2.3,  2.7,  3.4,  3.2,  2.8,  3.8, -0.4,
        1.6,  3.2,  2.1,  1.5,  1.5])

In [18]:
inflation.index

RangeIndex(start=0, stop=16, step=1)

In [19]:
inflation.index.values

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15],
      dtype=int64)

In [20]:
inflation = pd.Series({1999 : 2.2, 2000 : 3.4, 2001 : 2.8, 2002 : 1.6, 2003 : 2.3, 2004 : 2.7, 2005 : 3.4, 2006 : 3.2, 2007 : 2.8, 2008 : 3.8, 2009 : -0.4, 2010 : 1.6, 2011 : 3.2, 2012 : 2.1, 2013 : 1.5, 2014 : 1.6, 2015 : np.nan})

In [21]:
inflation

1999    2.2
2000    3.4
2001    2.8
2002    1.6
2003    2.3
2004    2.7
2005    3.4
2006    3.2
2007    2.8
2008    3.8
2009   -0.4
2010    1.6
2011    3.2
2012    2.1
2013    1.5
2014    1.6
2015    NaN
dtype: float64

In [22]:
inflation = pd.Series((2.2, 3.4, 2.8, 1.6, 2.3, 2.7, 3.4, 3.2, 2.8, 3.8, 
-0.4, 1.6, 3.2, 2.1, 1.6, 1.5))

In [23]:
inflation.index = pd.Index(range(1999, 2015))

In [25]:
inflation[2015] = np.nan

In [26]:
inflation.index.name = "Year" 
inflation.name = "%"
inflation

Year
1999    2.2
2000    3.4
2001    2.8
2002    1.6
2003    2.3
2004    2.7
2005    3.4
2006    3.2
2007    2.8
2008    3.8
2009   -0.4
2010    1.6
2011    3.2
2012    2.1
2013    1.6
2014    1.5
2015    NaN
Name: %, dtype: float64

In [27]:
inflation.head()

Year
1999    2.2
2000    3.4
2001    2.8
2002    1.6
2003    2.3
Name: %, dtype: float64

In [28]:
inflation.tail()

Year
2011    3.2
2012    2.1
2013    1.6
2014    1.5
2015    NaN
Name: %, dtype: float64

In [6]:
import pandas as pd

In [33]:
alco2009 = pd.read_csv("모두의 데이터과학 with 파이썬/예제파일/niaaa-report2009.csv", index_col="State")
alco2009

Beer  Wine  Spirits
State                                    
Alabama               1.20  0.22     0.58
Alaska                1.31  0.54     1.16
Arizona               1.19  0.38     0.74
Arkansas              1.07  0.17     0.60
California            1.05  0.55     0.73
Colorado              1.22  0.46     1.00
Connecticut           0.89  0.59     0.86
Delaware              1.31  0.57     1.25
District of Columbia  1.26  1.00     1.64
Florida               1.21  0.48     0.92
Georgia               1.08  0.25     0.64
Hawaii                1.30  0.53     0.75
Idaho                 1.05  0.92     0.70
Illinois              1.22  0.39     0.73
Indiana               1.09  0.25     0.73
Iowa                  1.42  0.18     0.72
Kansas                1.18  0.14     0.67
Kentucky              1.11  0.18     0.65
Louisiana             1.50  0.28     0.85
Maine                 1.24  0.42     0.83
Maryland              0.97  0.37     0.87
Massachusetts         1.02  0.61     0.84
Michigan              1.10  0.31     0.80
Minnesota             1.19  0.37     1.04
Mississippi           1.41  0.11     0.71
Missouri              1.30  0.30     0.83
Montana               1.66  0.45     0.88
Nebraska              1.46  0.20     0.68
Nevada                1.57  0.58     1.15
New Hampshire         1.72  0.84     1.82
New Jersey            0.92  0.57     0.87
New Mexico            1.37  0.32     0.74
New York              0.91  0.46     0.69
North Carolina        1.10  0.34     0.58
North Dakota          1.63  0.25     1.16
Ohio                  1.28  0.26     0.47
Oklahoma              1.18  0.18     0.58
Oregon                1.28  0.49     0.82
Pennsylvania          1.35  0.23     0.61
Rhode Island          1.10  0.53     0.92
South Carolina        1.36  0.24     0.77
South Dakota          1.53  0.22     0.88
Tennessee             1.05  0.21     0.57
Texas                 1.42  0.28     0.58
Utah                  0.70  0.17     0.46
Vermont               1.36  0.63     0.70
Virginia              1.11  0.43     0.59
Washington            1.09  0.51     0.74
West Virginia         1.24  0.10     0.45
Wisconsin             1.49  0.31     1.16
Wyoming               1.45  0.22     1.10

In [34]:
alco2009["Wine"].head()

State
Alabama       0.22
Alaska        0.54
Arizona       0.38
Arkansas      0.17
California    0.55
Name: Wine, dtype: float64

In [35]:
alco2009.Beer.tail()

State
Virginia         1.11
Washington       1.09
West Virginia    1.24
Wisconsin        1.49
Wyoming          1.45
Name: Beer, dtype: float64

In [36]:
alco2009["Total"] = 0
alco2009.head()

Beer  Wine  Spirits  Total
State                                 
Alabama     1.20  0.22     0.58      0
Alaska      1.31  0.54     1.16      0
Arizona     1.19  0.38     0.74      0
Arkansas    1.07  0.17     0.60      0
California  1.05  0.55     0.73      0

In [37]:
alco2009.columns.values

array(['Beer', 'Wine', 'Spirits', 'Total'], dtype=object)

In [38]:
alco2009.index.values

array(['Alabama', 'Alaska', 'Arizona', 'Arkansas', 'California',
       'Colorado', 'Connecticut', 'Delaware', 'District of Columbia',
       'Florida', 'Georgia', 'Hawaii', 'Idaho', 'Illinois', 'Indiana',
       'Iowa', 'Kansas', 'Kentucky', 'Louisiana', 'Maine', 'Maryland',
       'Massachusetts', 'Michigan', 'Minnesota', 'Mississippi',
       'Missouri', 'Montana', 'Nebraska', 'Nevada', 'New Hampshire',
       'New Jersey', 'New Mexico', 'New York', 'North Carolina',
       'North Dakota', 'Ohio', 'Oklahoma', 'Oregon', 'Pennsylvania',
       'Rhode Island', 'South Carolina', 'South Dakota', 'Tennessee',
       'Texas', 'Utah', 'Vermont', 'Virginia', 'Washington',
       'West Virginia', 'Wisconsin', 'Wyoming'], dtype=object)

In [39]:
alco2009.reset_index().set_index("Beer").head()

State  Wine  Spirits  Total
Beer                                  
1.20     Alabama  0.22     0.58      0
1.31      Alaska  0.54     1.16      0
1.19     Arizona  0.38     0.74      0
1.07    Arkansas  0.17     0.60      0
1.05  California  0.55     0.73      0

In [40]:
alco2009.ix["Nebraska"]

C:\Users\user\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#ix-indexer-is-deprecated
  """Entry point for launching an IPython kernel.


Beer       1.46
Wine       0.20
Spirits    0.68
Total      0.00
Name: Nebraska, dtype: float64

In [41]:
"Samoa" in alco2009.index

False

In [42]:
"Alabama" in alco2009.index

True

In [44]:
alco2009 = pd.read_csv("모두의 데이터과학 with 파이썬/예제파일/niaaa-report2009.csv", index_col="State")
"Samoa" in alco2009.index

False

In [49]:
# 철자 'S'로 시작하는 주의 리스트 만들기
s_states = [state for state in alco2009.index if state[0] == 'S'] + ["Samoa"]
drinks = list(alco2009.columns) + ["Water"]
nan_alco = alco2009.reindex(s_states, columns=drinks).fillna(method="ffill")
nan_alco

Beer  Wine  Spirits  Water
State                                     
South Carolina  1.36  0.24     0.77    NaN
South Dakota    1.53  0.22     0.88    NaN
Samoa           1.53  0.22     0.88    NaN

In [17]:
alco = pd.read_csv("모두의 데이터과학 with 파이썬/예제파일/niaaa-report.csv", index_col=["State","Year"])
alco

Beer  Wine  Spirits
State   Year                     
Alabama 1977  0.99  0.13     0.84
        1978  0.98  0.12     0.88
        1979  0.98  0.12     0.84
        1980  0.96  0.16     0.74
        1981  1.00  0.19     0.73
...            ...   ...      ...
Wyoming 2005  1.21  0.23     0.97
        2006  1.47  0.23     1.05
        2007  1.49  0.23     1.10
        2008  1.54  0.23     1.12
        2009  1.45  0.22     1.10

[1683 rows x 3 columns]

In [20]:
alco.index = multi

In [21]:
alco.ix['Wyoming'].head() 

C:\Users\user\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#ix-indexer-is-deprecated
  """Entry point for launching an IPython kernel.


Beer  Wine  Spirits
Year                     
1977  1.79  0.21     1.32
1978  1.82  0.22     1.36
1979  1.86  0.22     1.30
1980  1.85  0.24     1.32
1981  1.91  0.24     1.27

In [22]:
alco.ix['Wyoming', 1999] 

C:\Users\user\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#ix-indexer-is-deprecated
  """Entry point for launching an IPython kernel.


Beer       1.41
Wine       0.18
Spirits    0.84
Name: (Wyoming, 1999), dtype: float64

In [24]:
tall_alco = alco.stack()
tall_alco.index.names = ["State", "Year", "Drink"] 
tall_alco.head(10)

State    Year  Drink  
Alabama  1977  Beer       0.99
               Wine       0.13
               Spirits    0.84
         1978  Beer       0.98
               Wine       0.12
               Spirits    0.88
         1979  Beer       0.98
               Wine       0.12
               Spirits    0.84
         1980  Beer       0.96
dtype: float64

In [53]:
wide_alco = alco.unstack()
wide_alco.head()
---------------------------------------


alco = pd.read_csv("niaaa-report.csv")
alco.pivot("Year", "State", "Wine")


nan_alco.dropna(how="all")


nan_alco.dropna(how="all", axis=1)


nan_alco.dropna()


nan_alco.isnull()


nan_alco.notnull()
---------------------------------------


sp = nan_alco['Spirits'] # 결측값이 있는 열을 선택했다.
clean = sp.notnull() # 결측값이 없는 행
sp[-clean] = sp[clean].mean() # 정상적인 값의 평균으로 결측치를 보정한다.
nan_alco


nan_alco.fillna(0)


nan_alco.fillna(method="ffill")
---------------------------------------


population = pd.read_csv("population.csv", index_col="State")
population.head()



df = pd.merge(alco2009.reset_index(), 
     population.reset_index()).set_index("State")
df.head()


df = pd.merge(alco2009, population, left_index=True, right_index=True)
df.head()


population.join(alco2009).tail(10)


pd.concat([alco2009, population], axis=1).tail()
---------------------------------------


pop_ca = pd.read_csv("demo02a-eng.csv", index_col="State")
pop_ca


pop_na = pd.concat([population, pop_ca], keys=["US", "CA"]) 
pop_na.index.names = ("Country", "State")
pop_na
---------------------------------------


population.sort_index().head()


population.sort_values("Population").head()


pop_by_state = population.sort_index()
pop_by_state.rank().head()
---------------------------------------


alco2009.max() 


alco2009.min(axis=1) 


alco2009.sum() 
---------------------------------------


내려받은 예제 파일에 실습을 위한 multi.txt 파일이 있습니다.

multi.txt를 참고하세요.
---------------------------------------


alco.index = multi

alco['Total'] = alco.Beer + alco.Wine + alco.Spirits
---------------------------------------


import pickle
with open(“alco.pickle”, “wb”) as oFile:
  pickle.dump(alco, oFile)

alco.ix['Hawaii'].cumsum().head()


alco.ix['Hawaii'].diff().head()
---------------------------------------


dna = "AGTCCGCGAATACAGGCTCGGT"
dna_as_series = pd.Series(list(dna), name="genes")
dna_as_series.head()


dna_as_series.unique()


dna_as_series.value_counts().sort_index()


valid_nucs = list("ACGT")
dna_as_series.isin(valid_nucs).all()
---------------------------------------


alco["Total"] = alco.Wine + alco.Spirits + alco.Beer
alco.head()


np.log10(alco.Total).head()


dna = "AGTCCGCGAATACAGGCTCGGT"
dna1 = dna.replace("C", "")
dna2 = dna.replace("T", "")
dna_as_series1 = pd.Series(list(dna1), name="genes") # C가 제거되었다.
dna_as_series2 = pd.Series(list(dna2), name="genes") # T가 제거되었다.
dna_as_series1.value_counts() + dna_as_series2.value_counts()
---------------------------------------


# “Year” 열로 데이터를 묶고자 한다.
alco_noidx = alco.reset_index()
sum_alco = alco_noidx.groupby("Year").sum() 
sum_alco.tail()
---------------------------------------


내려받은 예제 파일에 실습을 위한 state2reg.txt 파일이 있습니다.

state2reg.txt


state2reg = {'Connecticut' : 'NORTHEAST', 'Maine' : 'NORTHEAST', 'Massachusetts' : 'NORTHEAST', 'New Hampshire' : 'NORTHEAST', 'Rhode Island' : 'NORTHEAST', 'Vermont' : 'NORTHEAST', 'New Jersey' : 'NORTHEAST', 'New York' : 'NORTHEAST','Pennsylvania': 'NORTHEAST', 'Illinois': 'MIDWEST', 'Indiana': 'MIDWEST', 'Michigan': 'MIDWEST', 'Ohio': 'MIDWEST', 'Wisconsin': 'MIDWEST', 'Iowa': 'MIDWEST', 'Kansas': 'MIDWEST',

'Minnesota': 'MIDWEST', 'Missouri': 'MIDWEST', 'Nebraska': 'MIDWEST', 'North Dakota': 'MIDWEST', 'South Dakota': 'MIDWEST', 'Delaware': 'SOUTH',

'District of Columbia': 'SOUTH', 'Florida': 'SOUTH', 'Georgia': 'SOUTH', 'Maryland': 'SOUTH', 'North Carolina': 'SOUTH', 'South Carolina': 'SOUTH',

'Virginia': 'SOUTH', 'West Virginia': 'SOUTH', 'Alabama': 'SOUTH', 'Kentucky': 'SOUTH', 'Mississippi': 'SOUTH', 'Tennessee': 'SOUTH', 'Arkansas': 'SOUTH',

'Louisiana': 'SOUTH', 'Oklahoma': 'SOUTH', 'Texas': 'SOUTH', 'Arizona': 'WEST', 'Colorado': 'WEST', 'Idaho': 'WEST', 'Montana': 'WEST', 'Nevada': 'WEST',

'New Mexico': 'WEST', 'Utah': 'WEST', 'Wyoming': 'WEST', 'Alaska': 'WEST', 'California': 'WEST', 'Hawaii': 'WEST', 'Oregon': 'WEST', 'Washington': 'WEST'}
---------------------------------------


alco2009.groupby(state2reg).mean()


cats = pd.cut(alco2009['Wine'], 3).head()
cats


cats = pd.cut(alco2009['Wine'], 3, labels=("Low", "Moderate", "Heavy"))
cats.head()


cats = pd.cut(alco2009['Wine'], 3, labels=False).head()
cats


quants = pd.qcut(alco2009['Wine'], 3, labels=("Low", "Moderate", "Heavy"))
quants.head()


pd.get_dummies(pd.Series(state2reg)).sort_index().head()


with_state = alco2009.reset_index()
abbrevs = with_state["State"].map(lambda x: x[:3].upper())
abbrevs.head()


wine_state = alco2009["Wine"] > alco2009["Wine"].mean()
beer_state = alco2009["Beer"] > alco2009["Beer"].mean()
pd.crosstab(wine_state, beer_state)
---------------------------------------


# regions.csv 파일을 읽어온다. 내려받은 region.csv 파일을 사용한다.
regions = pd.read_csv("regions.csv",  
                     header=None,
                     names=("region", "division", "state"))
state2reg_series = regions.ffill().set_index("state")["region"]
state2reg_series.head()
---------------------------------------


state2reg = state2reg_series.to_dict()
state2reg
---------------------------------------

# regions.csv를 읽어온다.
chunker = pd.read_csv("regions.csv", chunksize=5,
                      header=None, names=("region", "division", "state"))

accum = pd.Series()
for piece in chunker:
    counts = piece["region"].value_counts()
    accum = accum.add(counts, fill_value=0)

accum

==========================================================================

SyntaxError: invalid character in identifier (<ipython-input-53-e8390c35bae5>, line 11)